TM-86: List + read vocab
TailoredMediaProject/tm-knowledge-store pull request #12
Opened 2021-12-13 14:12 UTC by ManuelTS

Closes TM-86, read and list vocabs

2021-12-13 15:36 UTC, ManuelTS commented on be/src/controlers/rest.router.ts
> +  /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z$/.test(dateString);
I did not change this to creating a date object as this will be done later on in the api layer and `new Date()` supports other date format strings too, but we only support the UTC format in the examples of `openapi.yaml`. One question remains, in JS the `new Date().toISOString()`prints e.g. `2021-12-13T15:34:47.869Z`, but in the `openapi.yaml` we are missing the MS. What is wanted, the `openapi.yaml` version without MS?

2021-12-13 20:35 UTC, ja-fra requested changes

2021-12-13 20:35 UTC, ja-fra commented on be/src/controlers/rest.router.ts
> +  /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z$/.test(dateString);
Let's be generous: Whatever `Date()` can parse we accept, even if if doesn't conform strictly with the API-Spec.

2021-12-13 20:35 UTC, ja-fra commented on be/src/services/vocabulary.service.ts
> +    public async listVocab(query: ListQueryModel, id?: string | ObjectId): Promise<Vocabulary[]> {
IMHO this function should return a `Promise<ListingResult<Vocabulary>>` where
```
interface ListingResult<T> {
    offset: number
    next: number
    totalItems: number
    items: T[]
}
```

2021-12-13 20:35 UTC, ja-fra commented on be/src/services/vocabulary.service.ts
> +                            $regex: `${query.text}`,
User-Input needs to be escapted!

2021-12-13 20:35 UTC, ja-fra commented on be/src/models/query-list.model.ts
> +import {DateTime} from '../generated';
This is an internal model, so there should be no reference to the API-Layer.

Use `Date` and perform the conversion DateTime -> Date in the API-Layer

2021-12-13 20:35 UTC, ja-fra commented on be/src/controlers/rest.router.ts
> +const createReadOrListResponse = (items: VocabularyDTO[], id: string | undefined, offset: string | undefined, isRead: boolean): any => {
Please clean up the signature of this method (unused params)

2021-12-14 07:33 UTC, ManuelTS commented on be/src/services/vocabulary.service.ts
> +    public async listVocab(query: ListQueryModel, id?: string | ObjectId): Promise<Vocabulary[]> {
> IMHO this function should return a `Promise<ListingResult<Vocabulary>>` where
> 
> ```
> interface ListingResult<T> {
>     offset: number
>     next: number
>     totalItems: number
>     items: T[]
> }
> ```

@ja-fra What does next stand for? In the spec is

``` 
{
  "offset": 0,
  "rows": 10,
  "totalItems": 0,
  "items": [
    {
      "id": "string",
      "created": "2021-11-29T16:02:17Z",
      "lastModified": "2021-11-29T16:02:17Z",
      "label": "string",
      "description": "string",
      "entityCount": 0
    }
  ]
}
```
defined as return type with `rows`.

2021-12-14 08:38 UTC, ja-fra commented on be/src/services/vocabulary.service.ts
> +    public async listVocab(query: ListQueryModel, id?: string | ObjectId): Promise<Vocabulary[]> {
`next = offset + items.length` but you can switch to `offset, rows` if you prefer...

2021-12-15 12:54 UTC, merged