TM-79: Update entities endpoint
TailoredMediaProject/tm-knowledge-store pull request #24
Opened 2021-12-16 10:23 UTC by ManuelTS

Closes TM-79.

2021-12-16 10:49 UTC, ja-fra requested changes

2021-12-16 10:49 UTC, ja-fra commented on be/.eslintcache
> +[{"/home/mts/Desktop/projects/tm-knowledge-store/be/src/app.ts":"1","/home/mts/Desktop/projects/tm-knowledge-store/be/src/controllers/health.router.ts":"2","/home/mts/Desktop/projects/tm-knowledge-st
I guess this should go to `.gitignore`

2021-12-16 10:49 UTC, ja-fra commented on openapi.yaml
> +          $ref: '#/components/responses/PreconditionRequired'
Please include this update also in other operations

2021-12-16 15:23 UTC, ja-fra approved these changes

2021-12-17 09:48 UTC, dan0bar approved these changes

2021-12-17 09:56 UTC, merged