TM-103: Implemented the count of the total number of vocabularies
TailoredMediaProject/tm-knowledge-store pull request #26
Opened 2021-12-16 14:43 UTC by janoliver20

2021-12-16 15:12 UTC, ja-fra requested changes

2021-12-16 15:12 UTC, ja-fra commented on be/src/services/vocabulary.service.ts
> +            this.countCollectionItems()
This does not provide the correct number: It not about _all_ the vocabularies, but those that match the query/filter...

2022-01-10 07:28 UTC, ManuelTS requested changes

2022-01-10 07:28 UTC, ManuelTS commented on be/src/services/entity.service.ts
> +      totalItems: size, // TODO
1. Remove the `TODO` comment
2. Using a variable with the same content as the above row is false, then we would not net totalItems at all. Instead:
3. We need the information of how many items are in total without any paging - no consideration of offset nor rows - are found for the filter with options on the DB. Is that correct @ja-fra ?

2022-01-10 07:37 UTC, ManuelTS requested changes

2022-01-10 07:37 UTC, ManuelTS commented on be/src/services/vocabulary.service.ts
> +      totalItems: size, // TODO
1. Remove the `TODO`comment
2. From my point of view, using the variable with the same content as the row above is wrong. Instead:
3. We need here the total items of the filter + options without any paging applied

2022-01-11 08:28 UTC, ManuelTS approved these changes

2022-01-11 08:30 UTC, ManuelTS approved these changes
Please fix the lint errors, but already approved

2022-01-11 08:38 UTC, merged