TM-92: Response entity with canonicalLink set
TailoredMediaProject/tm-knowledge-store pull request #40
Opened 2022-01-14 10:41 UTC by ManuelTS

2022-01-14 10:46 UTC, ja-fra commented on be/src/controllers/resolve.router.ts
> +  new KnowledgeResolveService([`https://${HOST}/kp/`, `http://${HOST}/kp/`]),
```suggestion
  new KnowledgeResolveService([`https://${HOST}/kb/`, `http://${HOST}/kb/`]),
```

2022-01-14 10:49 UTC, ja-fra requested changes

2022-01-14 10:49 UTC, ja-fra commented on be/src/models/constants.ts
> +export const HOST = 'data.tmedia.redlink.io';
Please make this configurable via `env`

2022-01-17 07:24 UTC, janoliver20 approved these changes

2022-01-17 08:13 UTC, dan0bar approved these changes

2022-01-17 09:21 UTC, merged